# Generated by Django 2.1.5 on 2019-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='score',
            field=models.CharField(default='Not calculated', max_length=200),
        ),
    ]
