# Generated by Django 2.1.5 on 2019-01-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_handout'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='definitions',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handout',
            name='definitions_order',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
