# Generated by Django 2.1.5 on 2019-01-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20190113_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
