# Generated by Django 2.1.5 on 2019-01-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_delete_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
